### ISSUE TITLE
Fix bookmark default position / view

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/autophagosomes-clem#4]
@tischi 
The current `view` / `position` in the bookmarks are incorrect:
- for 10spd, you added the view at some point, but I have corrected the resolution since, see #2, so this is outdated.
- for 10spdbaf, the `position` is not correct, because I forgot to account for the resolution ...

We should fix these 2. In general, it would be good to come up with a formula to determine the default position or view:
https://github.com/constantinpape/autophagosomes-clem/blob/master/mmb_utils/metadata.py#L69-L70

I would just take the center position, as is done right now, but correct it for the resolution.
Or would you rather have a `view` by default? How can I compute it from just the data shape and the resolution?

**Comment by tischi** [comment]
@constantinpape maybe we can close this one, because we have it as a duplicate somewhere else, don't we?

**Comment by constantinpape** [comment]
Yes, we have.
Also, we can just remove the `view/positions` from the bookmarks, because then BDV figures it out, correct?

**Comment by tischi** [comment]
Correct.
But, what I still need to implement is this "Home" button. 
I think this is important when people get lost. I think we have an issue for this...

**Comment by constantinpape** [comment]
Yes, ok I will check later and then close this issue.

**Comment by constantinpape** [comment]
I couldn't find a specific issue about the home button and made one:
https://github.com/mobie-org/mobie-viewer-fiji/issues/96
