### ISSUE TITLE
Check data on s3

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/autophagosomes-clem#5]
@tischi I have added the data to s3 now.
Let me know if you can open it in the platy browser remotely.
See Joseps mail for details on the bucket.

**Comment by tischi** [comment]
I can open the data and also parse all the new bookmarks.

It looks like your autophagosomes label mask image is more like as simple mask where all objects have the same label id 1.0 ?

**Comment by constantinpape** [comment]
> I can open the data and also parse all the new bookmarks.

Great!
Once we push the new MOBiE version next week, we can send the credentials to Ben and Jurgen so that they can take a look already :).

> It looks like your autophagosomes label mask image is more like as simple mask where all objects have the same label id 1.0 ?

Yes, these were some initial labels I got for the data, I just added them to see if the segmentation functionality works, we can ignore it for now.

**Comment by constantinpape** [comment]
Done.
