### ISSUE TITLE
Authentication missing

### ISSUE THREAD

**Issue by tischi** [constantinpape/autophagosomes-clem#6]
Hi @constantinpape,

Maybe you know, but just to tell you the authentication is missing here:

https://github.com/mobie-org/autophagosomes-clem-datasets/blob/master/data/10spd/images/remote/fibsem-10spd-raw.xml#L28

This leads to a crash right now, because the current code requires the field to exist.
Should I change it and default to anonymous if it is missing?

**Comment by constantinpape** [comment]
> Should I change it and default to anonymous if it is missing?

No, I think we should require it.
I will fix it for the data here.

**Comment by constantinpape** [comment]
It's called `Protected`, right?

**Comment by tischi** [comment]
Right

**Comment by constantinpape** [comment]
I updated and tested it, works :).
